sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: A4viXwDIdQBQed1RCz7idyzeTlwdaOyO4843NGZi66+gTvUOYnOiKDiofMu9BFJBhRCnvxo7luC5UNMr11vzZMHtSIbZn/kM0x3Qr3aH4sLAzqSvSAYPimiNYbmN8e/PnGZdmoRRB703SvOtw18c6OJKZ2vyCaIFcMFtdR6MlI11/0Y84XzCjh5bGaCRlvEWJID4zZ+XS2Vs/35z/bnXY1o88fKOqzIe4wXHEfND39PM7PJ7QGqCvilkoWmPx36EN7b+/xFkCij7RjYAAs+C0QRqaTmwvi0rlQksg23I10F29HAyFPu8Evyl9j/PlhmC3pOLdLsEjnHpn7FbrDuKtU1ndnwBVVDn0W0IKDFT9YnqRqpy4zE3DXRO5OJDjEGxRwzlrx3U9j4jxLaNd9UcTWSHKg2RFmchOswL5zIPMf6/428KjMqXITdu+xUUZ+qgoHchyFD4KwSamv2OfCr2FSbB1GB4eAOjpV66veIgRft8FEsP4op+dVvRZLCruiJ58azm8PGK+qstDJ8UA1JQj0o9CAYc7miNnNFqTJqeLJptG29S76+PxYTvvA5e7KOqKwC6ql9fhG8K1tcIZan3JaPrGYwUmLkckEJ2ErHQASmiMijmZh9rX9Zv9ZVZbvu4bPMKpubeEZDmgp2+e4XrQ9ZKNVuig4WoBMXsq+HsXJU=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Miss-Billy-s-Decision_362
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy